# Generated by Django 5.1.3 on 2024-11-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortContent', models.TextField()),
                ('mainContent', models.TextField()),
                ('img', models.ImageField(upload_to='imgs/%Y/%m/%d/')),
                ('isActaive', models.BooleanField(default=True)),
            ],
        ),
    ]
