# Generated by Django 5.1.3 on 2024-11-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_service_shortcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='shortContent',
            field=models.TextField(),
        ),
    ]
