# Generated by Django 5.1.3 on 2024-11-14 12:11

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_service_shortcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.SmallIntegerField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=75)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='mainContent',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='shortContent',
            field=tinymce.models.HTMLField(),
        ),
    ]
