# Generated by Django 4.2.1 on 2024-11-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_order_service_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='shortContent',
            field=models.TextField(),
        ),
    ]
