# Generated by Django 5.1.3 on 2024-11-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_order_service_alter_service_shortcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceClass',
            field=models.CharField(default='Delete this and write the class of this service', max_length=50),
        ),
    ]
